### PR TITLE
Added warning for NaNs

### LINKED ISSUE #200: Check for NaNs and raise warning
As discussed with @observingClouds  and @milankl, and raised in this [`BitInformation.jl` issue](https://github.com/milankl/BitInformation.jl/issues/47): the elements in an array should be checked whether they are finite and raise a **warning** if they are not. As having many `NaN`s in the dataset may yield unexpected results.

A check could be using [`is_null()`](https://docs.xarray.dev/en/stable/generated/xarray.Dataset.isnull.html#xarray.Dataset.isnull) from `xarray` like:
```python
ds.is_null().sum()
```
Or perhaps by iterating through a dataset and issuing a warning upon encountering the first `NaN` value.

### PR DESCRIPTION
**Pull request by Bhairvi23**
Added warning for the first encountered NaN value.
Closes #200

### CODE REVIEW

**Comment by observingClouds** [comment]
Hi @Bhairvi23,
Thank you for your first contribution to xbitinfo 🎉 The PR looks good so far and the failure seems to come from the newest changes to xarray. Before this contribution can be merged we need to do a few more things:
- [ ] remove the .DS_Store file that has been accidentally been committed
- [ ] add your changes to the CHANGELOG.md
- [ ] add a simple test to check whether or not the warning will actually be raised.

**Comment by observingClouds** [comment]
@Bhairvi23 I just updated your branch with a fix for the doctests. Now the tests all pass 🎉 If you could address above mentioned points we are ready to merge this.

**Comment by Bhairvi23** [comment]
@observingClouds I am unable to find the .DS_Store file. I can see that there has been some changes but I cant seem to locate it.

**Comment by observingClouds** [comment]
Hi @Bhairvi23 ,
The file is likely hidden on your system. You can see it with `ls -a`. To remove the file from your PC and the git you could do `git rm .DS_store` and commit the changes afterwards as usual.

**Comment by milankl** [comment]
The `.DS_Store` file is still in the commits though, @Bhairvi23 can you try to delete it? It doesn't show up for me for some reason...

**Comment by observingClouds** [comment]
Sry @Bhairvi23 I just recognise that this issue will already be addressed with https://github.com/observingClouds/xbitinfo/pull/260 which was unfortunately not linked to #200

**Pull request closed without merging**
