### PR TITLE
Replaced inflevels with keepbits.

### LINKED ISSUE #76: add `bitround_along_dim(keepbits=[])` to be used instead of `inflevels=[]`
probably it would be better when allowing another keyword: `keepbits=[]` which could be used instead of `inflevels=[]`, Fig 3 Kloewer use keepbits I guess. with inflevels, you may end up with the same bitrounding for different levels.

_Originally posted by @aaronspring in https://github.com/observingClouds/bitinformation_pipeline/issues/73#issuecomment-1109578055_

### PR DESCRIPTION
**Pull request by wntrsldr0x01**
Fixes #76

### CODE REVIEW

**Comment by observingClouds** [comment]
Hi @wntrsldr0x01,
Thank you for your interest in the project and this PR. I see that you have renamed `inflevel` to `keepbits`. The number of bits to keep (`keepbits`) and the information level (`inflevel`) are both describing how much _data_ should be kept, but are two different concepts. `Keepbits` directly influences the number of bits that shall be kept and not rounded. The inflevel is an abstraction layer above. It describes the amount of _information_ that should be preserve. Depending on region/variable/time the number of bits that need to be kept in order to preserve this information may vary. [`get_keepbit`](https://github.com/observingClouds/xbitinfo/blob/c917b4304e26a8cc69a9eabd2cc128287f8e7cd4/xbitinfo/xbitinfo.py#L375) contains the function to transform from `inflevel` to `keepbits`.

The idea in #76 is to add an additional option to provide `keepbits` directly instead of `inflevel`. Thinking about this issue more, I would still keep the current behaviour and add the suggestion from #76 as an additional possibility to call `bitround_along_dim`.

**Comment by wntrsldr0x01** [comment]
Hello @observingClouds, from your comment I understood that keepbits has to be added rather than to be replaced with inflevel. My question is, adding keepbits alongside other variables [here](https://github.com/observingClouds/xbitinfo/blob/main/xbitinfo/bitround.py#L139), is the only thing to do? Also is there a chat software that I can join for this repo?

**Comment by observingClouds** [comment]
@wntrsldr0x01, that's correct. `Keepbits` should be an additional option to `inflevel`. The function is called via https://github.com/observingClouds/xbitinfo/blob/a2e52325cbe21c615d722f8b2ac9845549ff92fd/xbitinfo/graphics.py#L8. The option to use `keepbits` should also be implemented there.

There is no chat client yet. We will try to set something up soon.

**Comment by wntrsldr0x01** [comment]
@observingClouds please take a look.

**Comment by observingClouds** [comment]
@wntrsldr0x01 please familiarise yourself a bit more with the principles and theory behind this project. The best way is probably to read and watch the linked resources on the README page and experiment with the code yourself. Maybe you have your own dataset you would like to test. This PR is just replacing `inflevels` with `keepbits`. As mentioned above, these are different concepts.

**Comment by observingClouds** [comment]
Hi @wntrsldr0x01,
I'm closing this PR for now as it does not fix the issue yet. Please feel free to reopen it or create an issue if there is something unclear in the documentation.

**Pull request closed without merging**
