### PR TITLE
Add warning for quantized variables

### LINKED ISSUE #202: Flagging quantised input data formats
### Description

As discussed with @milankl and @Ishaanj18 the calculation of the bitwise information should be calculated on the 'rounded' bit-representation if rounding has been applied. In case of linear quantisation for example, the bitinformation should be calculated from the integer representation and only afterwards converted to float by applying the offset parameter and scale factor.

A first step to implement this, could be to raise a warning if the `scale` and `offset` attribute are found in the metadata of the dataset.

In a second step, the dataset should be reopened without applying the `scale` and `offset` parameter, which most libraries do per default.

### PR DESCRIPTION
**Pull request by JoelJaeschke**
This lets a user know that the variable in question is stored as a quantized integer, but loaded as a float, which will cause the calculation of the bit-information to yield bogus results depending on the data. Fixes #202

### CODE REVIEW

**Comment by observingClouds** [comment]
Hi @JoelJaeschke,
Welcome 👋 . Thanks for the PR. At first sight it looks good. I will have to fix some tests upstream and will come back to you once that is done.
Cheers,
Hauke

**Comment by JoelJaeschke** [comment]
Hi @observingClouds,

I did not run the test suite fully, so CI caught some stuff I failed to account for. I have pushed a new version that is more defensive in the way it does its checks. There are still two errors in the test I added when calling the Julia implementation, but I feel like those may be upstream errors? I don't have too much experience with how the code works yet, so forgive me if I have introduced those.

Best
Joel

**Comment by observingClouds** [comment]
I fixed some upstream issues that were caused by the usage of integers. The remaining failure of the CI can be traced back to https://github.com/milankl/BitInformation.jl/issues/50.

You were "lucky" and hit some cases we haven't tested for before. We need to address these and can merge your contribution afterwards (hoping that no other issues occur).

Could you, @JoelJaeschke, in the meantime add a short description of your PR to the CHANGELOG.md? Thanks!

**Comment by observingClouds** [comment]
@JoelJaeschke it took a few iterations but with the upstream changes that I merged into this branch the tests now succeed 😄

**Comment by observingClouds** [comment]
Congrats @JoelJaeschke on your first contribution to xbitinfo and welcome to the community :tada: Thank you very much for your time and effort, looking forward to any future inputs!

**Pull request merged**
