### PR TITLE
typos

### PR DESCRIPTION
**Pull request by aaronspring**
- cleanup
- or do we want to keep cli for one purpose?
- anything else which can be deleted?

### CODE REVIEW

**Comment by observingClouds** [comment]
It's fine to delete the cli for now. I used it just for testing in the beginning and we might quickly add it back when we decide to work on a cli.

**Comment by observingClouds** [comment]
Would this be a good place to unify the docstrings a little? We are changing a lot between small and capital letters in the description of arguments. I think, they should be all captialized.

**Comment by aaronspring** [comment]
Ok. Go for it

**Review by observingClouds — APPROVED** [review]
Done. I included my suggestions.

**Pull request merged**
