### PR TITLE
signed_exponent only for floats

### LINKED ISSUE #206: Apply signed_exponent only for floats and not for integers
To make xbitinfo also work with integers, the signed_exponent function should only be applied in case the data variable contains a float datatype.

https://github.com/observingClouds/xbitinfo/blob/e133caaa067740998c2e784e759f17ae2611cc51/xbitinfo/xbitinfo.py#L296

based on discussion with @ayoubft, @milankl

### PR DESCRIPTION
**Pull request by milankl**
fixes #206 

@Ishaanj18 can you test this?

### CODE REVIEW

**Comment by milankl** [comment]
Also, I'm not sure whether the signed exponent is actually acting in-place? There's probably somewhere a copy triggered, but you also wrote a few `views` so I'm not sure about this

**Comment by observingClouds** [comment]
Thanks @milankl . Float16 should work. I'm trying to fix the annoying segfault that is caused due to some unknown reasons in any of the recent tests...

**Comment by Ishaanj18** [comment]
I tried testing the code, we don't get the error mentioned in #208. But when I keep my astype as let's say f2 , I get the below error- 
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[27], line 1
----> 1 info = `xb.get_bitinformation(encoded_ds,dim='y',implementation="python")`
      2 xb.plot_bitinformation(info)

File ~\xbitinfo\xbitinfo\xbitinfo.py:236, in get_bitinformation(ds, dim, axis, label, overwrite, implementation, **kwargs)
    234         info_per_bit[var] = info_per_bit_var
    235 elif implementation == "python":
--> 236     info_per_bit_var = _py_get_bitinformation(ds, var, axis, dim, kwargs)
    237     if info_per_bit_var is None:
    238         continue

File ~\xbitinfo\xbitinfo\xbitinfo.py:299, in _py_get_bitinformation(ds, var, axis, dim, kwargs)
    297 # signed exponent conversion only for floats
    298 if X.dtype in (np.float16, np.float32, np.float64):
--> 299     X = pb.signed_exponent(X)
    300     print(X)
    301 X = X.astype(astype)

File ~\xbitinfo\xbitinfo\_py_bitinfo.py:93, in signed_exponent(A)
     91     esign = np.uint64(esign)
     92 esigned = esign | (eabs << sbits)
---> 93 B = (sf | esigned).view(np.int64)
     94 return B

File ~\anaconda3\envs\gsoc\Lib\site-packages\dask\array\core.py:2839, in Array.view(self, dtype, order)
   2835 mult = self.dtype.itemsize / dtype.itemsize
   2837 if order == "C":
   2838     chunks = self.chunks[:-1] + (
-> 2839         tuple(ensure_int(c * mult) for c in self.chunks[-1]),
   2840     )
   2841 elif order == "F":
   2842     chunks = (
   2843         tuple(ensure_int(c * mult) for c in self.chunks[0]),
   2844     ) + self.chunks[1:]

File ~\anaconda3\envs\gsoc\Lib\site-packages\dask\array\core.py:2839, in <genexpr>(.0)
   2835 mult = self.dtype.itemsize / dtype.itemsize
   2837 if order == "C":
   2838     chunks = self.chunks[:-1] + (
-> 2839         tuple(ensure_int(c * mult) for c in self.chunks[-1]),
   2840     )
   2841 elif order == "F":
   2842     chunks = (
   2843         tuple(ensure_int(c * mult) for c in self.chunks[0]),
   2844     ) + self.chunks[1:]

File ~\anaconda3\envs\gsoc\Lib\site-packages\dask\array\core.py:2970, in ensure_int(f)
   2968 i = int(f)
   2969 if i != f:
-> 2970     raise ValueError("Could not coerce %f to integer" % f)
   2971 return i

ValueError: Could not coerce 23.500000 to integer``
```

**Comment by Ishaanj18** [comment]
[conus-1.pdf](https://github.com/observingClouds/xbitinfo/files/11752955/conus-1.pdf)

**Review by observingClouds — APPROVED** [review]

**Pull request merged**
