### PR TITLE
separate dependencies

### LINKED ISSUE #267: Separation of dependencies
Dependencies of tests, documentation, setup and usage got a bit mixed up over time. It would be good to separate the dependencies again.

- https://github.com/observingClouds/xbitinfo/blob/main/docs/environment.yml
- https://github.com/observingClouds/xbitinfo/blob/main/environment.yml
- https://github.com/observingClouds/xbitinfo/blob/main/requirements.txt
- https://github.com/observingClouds/xbitinfo/blob/main/setup.py

### PR DESCRIPTION
**Pull request by AryanBakliwal**
# Separation of dependencies

fixes #267 

With reference from setup.py, added tests/environment.yaml and updated docs/environment.yaml

### CODE REVIEW

**Comment by AryanBakliwal** [comment]
Hi @observingClouds, please review :)

**Review by observingClouds — CHANGES_REQUESTED** [review]
@AryanBakliwal this is coming along nicely! Some tests are still failing though. I think the issue here is that the mamba environments are named in the respective environment.yml files like `xbitinfo-tests`, `xbitinfo-docs` and do not match the `activate-environment`. The later should be adapted accordingly and should then work.

Could you try that?

**Review by observingClouds — CHANGES_REQUESTED** [review]
Thanks for the adaptation. I would suggest to have test and doctest use the same environment (bitinfo-tests) and test-notebook actually bitinfo-docs.

**Comment by AryanBakliwal** [comment]
Hi @observingClouds, any clue why pytest and doctests are failing. I don't think I changed anything that would interfere with these

**Review by observingClouds — APPROVED** [review]
After some upstream updates, all tests are succeeding now! Thanks for your contribution to xbitinfo! 🎉

**Pull request merged**
