### PR TITLE
Fix 139

### LINKED ISSUE #139: `eraint_uvz` `test_full` fails
### Description

https://github.com/observingClouds/xbitinfo/actions/runs/3168552683/jobs/5159830575

```
assert compressed_size < ori_size
assert 9640058 < 4186398
```

Did defaults in `to_netcdf` change with new `xarray` release?

### PR DESCRIPTION
**Pull request by observingClouds**
fixes #139

### CODE REVIEW

**Comment by observingClouds** [comment]
A simple combination of the original encoding and output encoding does not work: https://github.com/observingClouds/xbitinfo/actions/runs/3170048268/jobs/5162370558#step:8:790
The issue is that not all encodings from the original dataset are valid encodings for the output engine (e.g. netcdf4 or zarr). [By default](https://github.com/pydata/xarray/blob/6b1d97ae16e4abaf4e29de2c19faca4239d0ab01/xarray/backends/api.py#L1247) each encoding is checked if it is valid for the specific engine and otherwise [raises an error](https://github.com/pydata/xarray/blob/6b1d97ae16e4abaf4e29de2c19faca4239d0ab01/xarray/backends/netCDF4_.py#L274-L280).

**Comment by observingClouds** [comment]
The easiest fix for now would be to copy all [`valid_encodings`](https://github.com/pydata/xarray/blob/6b1d97ae16e4abaf4e29de2c19faca4239d0ab01/xarray/backends/netCDF4_.py#L234-L243) from the input encoding to the output encoding.

**Comment by observingClouds** [comment]
@aaronspring what do you think of this fix? I'm basically calling some xarray backend function for netCDF4 and zarr that ensure that unsupported encodings are dropped before calling the respective library. As a consequence we can just merge the original encoding with `xbitinfo`s additional compression encoding.

https://github.com/observingClouds/xbitinfo/blob/4865978d646fad80553364921ebbff2862857d71/xbitinfo/save_compressed.py#L50

It's not nice to call a backend function, however this is meant to be only a temporary solution until https://github.com/pydata/xarray/issues/7129 and https://github.com/pydata/xarray/issues/7127 are fixed.

**Comment by aaronspring** [comment]
I like it. Does this mean that to_compressed_netcdf only works for netcdf4? Should we make it work also for other engines or would we need to rework xr.to_netcdf?

**Review by aaronspring — APPROVED** [review]

**Comment by observingClouds** [comment]
Good point @aaronspring . I think it should also work with other engines, but might drop a few extra encodings that are not allowed for the `netCDF4` library. The easiest would be to be able to set `raise_on_invalid ` to `False`, but I don't see a possibility to do so in `xr.Dataset.to_netcdf`. `raise_on_invalid` seems to be available in all inherited engine functions, like e.g. in `netCDF4`: https://github.com/pydata/xarray/blob/13c52b27b777709fc3316cf4334157f50904c02b/xarray/backends/netCDF4_.py#L224

**Comment by observingClouds** [comment]
I decided to make `netCDF4` the only allowed engine for now. This is the safest route. We can remove this restriction whenever there is a solution upstream, otherwise we would need to write a lot of functionality and tests that xarray already provides.

**Pull request merged**
