### PR TITLE
keep attrs of get_bitinformation

### LINKED ISSUE #154: keep attrs in get_bitinformation
- now we delete incoming attrs
- could be useful to keep
- change existing `units` to `input_units` and `long_name` to `input_long` or change `units` to `bitinfo_units` and `bitinfo_long_name`

### PR DESCRIPTION
**Pull request by aaronspring**
closes #154 

- changes `units` to `bitinfo_units`
- changes `long_name` to `bitinfo_long_name`
- keep input attrs

### CODE REVIEW

**Review by observingClouds — COMMENTED** [review]
Could you please explain why you would like to have the original `units` and `long_name` from the dataset? Do we loose these attributes when writing to netCDF/zarr?
The unit of the data that `info_per_bit = xb.get_bitinformation(ds)` contains is `1` and not e.g. `ms-1` if the input data was wind speed.

**Comment by aaronspring** [comment]
I want to keep long_name and all other attrs for context. Now we only have the variable name and no context from the input data. Original unit might not be very important

**Comment by aaronspring** [comment]
image

Now the bitinformation of z, in reference to what z actually is, is easier to understand IMO.

**Comment by observingClouds** [comment]
The attributes are preserved in `ds_bitrounded`:

```
In [11]: ds_bitrounded.u
Out[11]: 
<xarray.DataArray 'u' (month: 2, level: 3, latitude: 241, longitude: 480)>
array([[[[ 1.250000e+00,  1.250000e+00,  1.250000e+00, ...,
         [ 3.500000e+00,  3.500000e+00,  3.500000e+00, ...,
           3.750000e+00,  3.500000e+00,  3.500000e+00]]]], dtype=float32)
Coordinates:
  * longitude  (longitude) float32 -180.0 -179.2 -178.5 ... 177.8 178.5 179.2
  * latitude   (latitude) float32 90.0 89.25 88.5 87.75 ... -88.5 -89.25 -90.0
  * level      (level) int32 200 500 850
  * month      (month) int32 1 7
Attributes:
    number_of_significant_digits:                2
    units:                                       m s**-1
    long_name:                                   U component of wind
    standard_name:                               eastward_wind
    _QuantizeBitRoundNumberOfSignificantDigits:  3
```

**Comment by aaronspring** [comment]
I know. I just refered to info_per_bit the output from get_bitinformation

**Comment by observingClouds** [comment]
I don't really like this PR yet, mainly because the `units`, `long_name` and `standard_name` attributes are cf-conventions conform attributes that describe the attributes of the variable and not the ones they are derived from.
A compromise could be to prefix the attributes from the input dataset with e.g. `source_`, so that there would be `source_units = m**2 s**-2`, `source_standard_name = geopotential` etc. So instead of prefixing the bitinformation attributes, the original dataset attributes get a prefix. Would that help?

**Comment by aaronspring** [comment]
I like the source idea

**Review by observingClouds — APPROVED** [review]

**Pull request merged**
